---
# tasks file for ansible-role-oli-env/
#

- name: 
  file:
    name: ~/.ssh/
    mode: 0700
    state: directory

- name: Copy ssh config
  copy: 
    src: ssh_config
    dest: ~/.ssh/config

- name: SSH keys
  template:
    src: "{{item}}.j2"
    dest: "~/.ssh/{{item}}"
    mode: 0600
  loop:
        - id_ed25519
        - id_rsa
        - id_ed25519.pub
        - id_rsa.pub
